name: Deploy to Cloud Run from Source
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Add a fake 'git' to the PATH to force checkout to download zipball instead
        uses: actions/checkout@v3
        with:
         path: my_private_repository
      - name: Add a fake 'git' to the PATH to force checkout to download zipball instead
        shell: cmd
        run: |
          cd D:\actions-runner\_work\hello\hello\my_private_repository
          copy . D:\hello\web /y
     
